server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: Vaccination-Service
